// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_test;

namespace dotnet_test.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220602023458_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("dotnet_test.entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("senha")
                        .HasColumnType("longtext");

                    b.Property<string>("sobrenome")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("sobrenome")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "email@email.com1",
                            nome = "derex1",
                            senha = "derex32-1",
                            sobrenome = "xered1",
                            status = "on"
                        },
                        new
                        {
                            id = 2,
                            email = "email@email.com2",
                            nome = "derex2",
                            senha = "derex32-2",
                            sobrenome = "xered2",
                            status = "on"
                        },
                        new
                        {
                            id = 3,
                            email = "email@email.com3",
                            nome = "derex3",
                            senha = "derex32-3",
                            sobrenome = "xered3",
                            status = "on"
                        },
                        new
                        {
                            id = 4,
                            email = "email@email.com4",
                            nome = "derex4",
                            senha = "derex32-4",
                            sobrenome = "xered4",
                            status = "on"
                        },
                        new
                        {
                            id = 5,
                            email = "email@email.com5",
                            nome = "derex5",
                            senha = "derex32-5",
                            sobrenome = "xered5",
                            status = "on"
                        },
                        new
                        {
                            id = 6,
                            email = "email@email.com6",
                            nome = "derex6",
                            senha = "derex32-6",
                            sobrenome = "xered6",
                            status = "on"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
